standard_urn_admin_roles:
  - Administrator
  - SysAdmin
  - AccountAdmin

permission_status:
  - granted
  - pending
  - denied

authentication_types:
  - oauth1.0
  - basic

user_access_level:
  - admin
  - instructor

